# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rounding of Numbers (Fast Parallel Version)
#' 
#' @name Round_
#' @description
#' Fast version of rounding (when vector size >= 50000).
#' [ceiling_()] takes a single numeric argument x and returns a numeric vector
#' containing the smallest integers not less than the corresponding elements of
#' `x`. It is similar to [ceiling()].
#' 
#' [floor_()] takes a single numeric argument `x` and returns a numeric vector
#' containing the largest integers not greater than the corresponding elements of
#' `x`. It is similar to [floor()].
#' 
#' [trunc_()] takes a single numeric argument `x` and returns a numeric vector
#' containing the integers formed by truncating the values in `x` toward 0. It
#' is similar to [trunc()].
#'
#' @param x vector of numeric values
#' @param para the minimum length of `x` to use parallel computation (50000
#' by default)
#' 
#' @return A numeric vector, matrix, or data frame with the transformed values.
#' 
#' @details
#' They are **not** generic functions and do not process factor, Date, POSIXt,
#' difftime, complex, or S4 objects (use base R equivalent function instead).
#' Data frames are processed column-wise, providing each column is compatible.
#' All attributes are preserved.
#' 
#' @export
#' @seealso [ceiling()], [floor()], [trunc()]
#' @examples
#' floor_(c(1.23, 4.56, -7.89))
ceiling_ <- function(x, para = 5e4L) {
    .Call(`_svFast_ceiling_`, x, para)
}

#' @rdname Round_
#' @export
floor_ <- function(x, para = 5e4L) {
    .Call(`_svFast_floor_`, x, para)
}

#' @rdname Round_
#' @export
trunc_ <- function(x, para = 5e4L) {
    .Call(`_svFast_trunc_`, x, para)
}

#' Trigonometric Functions (Fast Parallel Version)
#' 
#' @name Trig_
#' @description
#' Fast version of trigonometric functions (when vector size >= 50000). They
#' respectively compute the cosine, sine, tangent, arc-cosine, arc-sine,
#' arc-tangent, and the two-argument arc-tangent.
#' 
#'  `cospi_(x)`, `sinpi_(x)`, and `tanpi_(x)`, compute `cos(pi*x)`,
#'  `sin(pi*x)`, and `tan(pi*x)`.
#'
#' @param x vector of numeric values
#' @param para the minimum length of `x` to use parallel computation (50000
#' by default)
#' 
#' @return A numeric vector, matrix, or data frame with the transformed values.
#' 
#' @details
#' They are **not** generic functions and do not process factor, Date, POSIXt,
#' difftime, complex, or S4 objects (use base R equivalent function instead).
#' Data frames are processed column-wise, providing each column is compatible.
#' All attributes are preserved.
#' 
#' @export
#' @seealso [cos()], [sin()], [tan()], [acos()], [asin()], [atan()], [atan2()]
#' @examples
#' cos_(1:5)
cos_ <- function(x, para = 5e4L) {
    .Call(`_svFast_cos_`, x, para)
}

#' @rdname Trig_
#' @export
sin_ <- function(x, para = 5e4L) {
    .Call(`_svFast_sin_`, x, para)
}

#' @rdname Trig_
#' @export
tan_ <- function(x, para = 5e4L) {
    .Call(`_svFast_tan_`, x, para)
}

#' @rdname Trig_
#' @export
acos_ <- function(x, para = 5e4L) {
    .Call(`_svFast_acos_`, x, para)
}

#' @rdname Trig_
#' @export
asin_ <- function(x, para = 5e4L) {
    .Call(`_svFast_asin_`, x, para)
}

#' @rdname Trig_
#' @export
atan_ <- function(x, para = 5e4L) {
    .Call(`_svFast_atan_`, x, para)
}

#' @rdname Trig_
#' @export
cospi_ <- function(x, para = 5e4L) {
    .Call(`_svFast_cospi_`, x, para)
}

#' @rdname Trig_
#' @export
sinpi_ <- function(x, para = 5e4L) {
    .Call(`_svFast_sinpi_`, x, para)
}

#' @rdname Trig_
#' @export
tanpi_ <- function(x, para = 5e4L) {
    .Call(`_svFast_tanpi_`, x, para)
}

#' Logarithm (Fast Parallel Version)
#' 
#' @name Log_
#' @description
#' Fast version of logarithmic and exponential functions (when vector size >=
#' 50000). [log_()] computes the natural logarithm of `x` (base `e` by default),
#' [log2_()] computes the base 2 logarithm, [log10_()] computes the base 10.
#' [log1p_(x)] computes `log(1 + x)` accurately even for small `x`.
#' 
#' [exp_()] computes the exponential function. [expm1_()] computes `exp(x) - 1`
#' accurately even for small `x`.
#'
#' @param x vector of numeric values
#' @param para the minimum length of `x` to use parallel computation (50000
#' by default)
#' 
#' @return A numeric vector, matrix, or data frame with the transformed values.
#' 
#' @details
#' They are **not** generic functions and do not process factor, Date, POSIXt,
#' difftime, complex, or S4 objects (use base R equivalent function instead).
#' Data frames are processed column-wise, providing each column is compatible.
#' All attributes are preserved.
#' 
#' @export
#' @seealso [log10()], [log2()], [log()], [log1p()], [exp()], [expm1()]
#' @examples
#' log_(1:5)
#' log_(1:5, base = 2.5)
log10_ <- function(x, para = 5e4L) {
    .Call(`_svFast_log10_`, x, para)
}

#' @rdname Log_
#' @export
log2_ <- function(x, para = 5e4L) {
    .Call(`_svFast_log2_`, x, para)
}

#' @rdname Log_
#' @export
log1p_ <- function(x, para = 5e4L) {
    .Call(`_svFast_log1p_`, x, para)
}

#' @rdname Log_
#' @export
exp_ <- function(x, para = 5e4L) {
    .Call(`_svFast_exp_`, x, para)
}

#' @rdname Log_
#' @export
expm1_ <- function(x, para = 5e4L) {
    .Call(`_svFast_expm1_`, x, para)
}

#' @rdname Log_
#' @param base the base of the logarithm (e = `exp(1)` by default)
#' @export
log_ <- function(x, base = 2.71828182845904523536028747135266250, para = 5e4L) {
    .Call(`_svFast_log_`, x, base, para)
}

#' @rdname Round_
#' @description [round_()] rounds the values in its first argument to the
#' specified number of decimal places (default 0). See 'Details' about "round
#' to even" in [round()] when rounding off a 5.
#' @param digits integer indication the number of decimal places ([round_()])
#' or significant digits ([signif_()]) to be used. For [round_()], negative
#' values are allowed and indicate rounding to a power of ten (-2 means
#' rounding to the nearest hundred), see [round()].
#' @export
#' @seealso [round()], [signif()]
round_ <- function(x, digits = 0L, para = 5e4L) {
    .Call(`_svFast_round_`, x, digits, para)
}

#' @rdname Round_
#' @description [signif_()] rounds the values in its first argument to the
#' specified number of significant digits.
#' @export
signif_ <- function(x, digits = 6L, para = 5e4L) {
    .Call(`_svFast_signif_`, x, digits, para)
}

